cache:
  paths:
    - .onceover
    - vendor/bundle

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --path vendor/bundle --jobs $(nproc) "${FLAGS[@]}"

rspec:
  script:
    - bundle exec onceover run spec

#rubocop:
#  script:
#    - bundle exec rubocop
